---
- name: apt update
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates

- name: set lsb-release
  command: "lsb_release -cs"
  register: result

- name: set lsb-release
  command: "dpkg --print-architecture"
  register: architecture

- name: create apt key dir
  file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: set apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: add apt repository
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }}  signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ result.stdout }} stable"
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli

- name: create docker dir
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "0777"

- name: /etc/docker/daemon.json 
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root

- name: Create containerd config file
  shell: containerd config default | tee /etc/containerd/config.toml

- name: containerd restart
  service:
    name: containerd
    state: restarted
    enabled: yes
- name: Enable systemd cgroup
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '{{item.regexp}}'
    line: '{{item.line}}'
    insertafter: '{{item.insertafter}}'
  with_items:
  - regexp: '            SystemdCgroup = false'
    line: '            SystemdCgroup = true'
    insertafter: 'plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options'
 
- name: Join docker group
  user:
    name: "1{{ ansible_user }}"
    groups: docker
    append: yes

- name:  systemctl daemon-reload 
  ansible.builtin.systemd:
    daemon_reload: yes

- name: docker restart
  service:
    name: docker
    state: restarted
    enabled: yes

