---
- name: apt update
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates

- name: set apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli

- name: create docker dir
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "777"

- name: /etc/docker/daemon.json 
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
- name: rm /etc/containerd/config.toml
  file:
    path: "/etc/containerd/config.toml"
    state: absent


- name:  systemctl daemon-reload 
  ansible.builtin.systemd:
    daemon_reload: yes

- name: docker restart
  service:
    name: docker
    state: restarted
    enabled: yes

