---
- name: Upgrade all package
  apt:
    upgrade: yes

- name: Install apt packages
  apt:
    name:
      - curl
      - apt-transport-https

- name: /etc/sysctl.d/99-kubernetes-cri.conf
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    owner: root
    group: root


- name: set apt key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name:
      - vim
      - git
      - wget

- name: Install kube packages
  apt:
    name:
      - kubelet=1.24.7-00
      - kubeadm=1.24.7-00
      - kubectl=1.24.7-00

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
