---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: generate ssh keypair
  openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}"
  register: result

- name: Set authorized key taken from generated keypair
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ hostvars[item].result.public_key }}"
  loop: "{{ groups['all'] }}"

