---
- name: copy copy-cred
  template:
    src: copy-cred.sh.j2
    dest: /home/{{ansible_user}}/copy-cred.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy install-cred
  template:
    src: install-cred.sh.j2
    dest: /home/{{ansible_user}}/install-cred.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy install-cred
  copy:
    src: kube-config-setup.sh
    dest: /home/{{ansible_user}}/kube-config-setup.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy install-cred
  copy:
    src: init.sh
    dest: /home/{{ansible_user}}/init.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
